kind: Service
apiVersion: v1
metadata:
  name: joona-service
spec:
  selector:
    app: joona
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31303
  type: LoadBalancer
